#!/bin/bash
#SBATCH -J metatrain_run
#SBATCH -o metatrain_run_%j.out
#SBATCH -e metatrain_run_%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=bx76@cornell.edu
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mem=8000
#SBATCH -t 4:00:00                     # Max runtime (4 hours)
#SBATCH --partition=jingjie
#SBATCH --get-user-env
source /share/apps/anaconda3/2022.10/etc/profile.d/conda.sh
conda activate reptile_env
# shellcheck disable=SC2164
cd ~/REPTILE/Models
python3 NN-MetaTrain.py
